import {
  Layers,
  Monitor,
  Layout,
  Smartphone,
  Code,
  FileText,
  ImageIcon,
  PresentationIcon,
  Type,
  Shapes,
  Box,
  VideoIcon as Vector,
  Move3dIcon as Assets3D,
  Building2,
  ShoppingBag,
  Users,
  HelpCircle,
  Sparkles,
} from "lucide-react"

export const MenuIcons = {
  FramerTemplates: <Layers className="h-5 w-5" />,
  WebUIKits: <Monitor className="h-5 w-5" />,
  Wireframes: <Layout className="h-5 w-5" />,
  MobileUIKits: <Smartphone className="h-5 w-5" />,
  CodedTemplates: <Code className="h-5 w-5" />,
  NotionTemplates: <FileText className="h-5 w-5" />,
  Mockups: <ImageIcon className="h-5 w-5" />,
  Presentations: <PresentationIcon className="h-5 w-5" />,
  Fonts: <Type className="h-5 w-5" />,
  Icons: <Shapes className="h-5 w-5" />,
  Objects: <Box className="h-5 w-5" />,
  Vector: <Vector className="h-5 w-5" />,
  Assets3D: <Assets3D className="h-5 w-5" />,
  OpenShop: <ShoppingBag className="h-5 w-5" />,
  BecomeAffiliate: <Users className="h-5 w-5" />,
  Contacts: <Building2 className="h-5 w-5" />,
  FAQ: <HelpCircle className="h-5 w-5" />,
  Magic: <Sparkles className="h-5 w-5" />,
}
