// Domain name components
const prefixes = [
  "freedom",
  "liberty",
  "patriot",
  "truth",
  "sovereign",
  "heritage",
  "faith",
  "american",
  "constitution",
  "republic",
  "eagle",
  "flag",
  "star",
  "stripe",
  "defend",
  "protect",
  "secure",
  "free",
  "brave",
  "bold",
  "strong",
  "united",
  "independent",
  "righteous",
  "just",
  "honest",
  "loyal",
  "faithful",
  "traditional",
  "conservative",
  "classic",
  "founding",
  "pioneer",
  "frontier",
  "heartland",
  "homeland",
  "nation",
  "country",
  "state",
  "local",
  "community",
  "family",
  "values",
  "principle",
  "virtue",
  "honor",
  "duty",
  "service",
  "sacrifice",
  "courage",
  "valor",
  "hero",
  "legacy",
  "history",
  "heritage",
  "tradition",
  "culture",
  "society",
  "citizen",
  "voter",
  "rights",
  "liberty",
  "justice",
  "law",
  "order",
  "peace",
  "security",
  "defense",
  "military",
  "veteran",
  "warrior",
  "fighter",
  "guardian",
  "shield",
  "sword",
  "arrow",
  "rifle",
  "gun",
  "ammo",
  "tactical",
  "strategic",
  "victory",
  "win",
  "triumph",
  "succeed",
  "achieve",
  "excel",
  "lead",
  "guide",
  "direct",
  "steer",
  "navigate",
  "chart",
  "map",
  "compass",
  "north",
  "south",
  "east",
  "west",
  "central",
  "united",
  "allied",
  "coalition",
  "federation",
  "union",
  "league",
  "alliance",
  "pact",
  "accord",
  "treaty",
  "agreement",
  "contract",
  "covenant",
  "pledge",
  "oath",
  "vow",
  "promise",
  "commit",
  "dedicate",
  "devote",
  "consecrate",
  "sanctify",
  "bless",
  "pray",
  "worship",
  "revere",
  "respect",
  "honor",
  "esteem",
  "admire",
  "digital",
  "cyber",
  "tech",
  "data",
  "info",
  "knowledge",
  "wisdom",
  "insight",
  "vision",
  "sight",
  "view",
  "perspective",
  "angle",
  "approach",
  "method",
  "system",
  "process",
  "procedure",
  "protocol",
  "standard",
  "benchmark",
  "measure",
  "metric",
  "index",
  "indicator",
  "signal",
  "sign",
  "symbol",
  "emblem",
  "badge",
  "insignia",
  "mark",
  "brand",
  "logo",
  "identity",
  "character",
  "nature",
  "essence",
  "core",
  "heart",
  "soul",
  "spirit",
  "mind",
  "intellect",
  "reason",
  "logic",
  "rational",
  "sensible",
  "practical",
  "pragmatic",
  "realistic",
  "grounded",
  "centered",
  "balanced",
  "stable",
  "steady",
  "firm",
  "solid",
  "strong",
  "robust",
  "resilient",
  "enduring",
  "lasting",
  "permanent",
  "eternal",
  "forever",
  "always",
  "constant",
  "consistent",
  "reliable",
  "dependable",
  "trustworthy",
  "credible",
  "authentic",
  "genuine",
  "real",
  "true",
  "actual",
  "factual",
  "verifiable",
  "provable",
  "demonstrable",
  "evident",
  "apparent",
  "clear",
  "obvious",
  "plain",
  "simple",
  "direct",
  "straight",
  "forward",
  "advance",
  "progress",
  "develop",
  "grow",
  "expand",
  "increase",
  "enhance",
  "improve",
  "upgrade",
  "elevate",
  "raise",
  "lift",
  "boost",
  "amplify",
  "magnify",
  "intensify",
  "strengthen",
  "fortify",
  "reinforce",
  "support",
  "uphold",
  "maintain",
  "sustain",
  "preserve",
  "conserve",
  "protect",
  "defend",
  "guard",
  "watch",
  "monitor",
  "observe",
  "survey",
  "scan",
  "search",
  "seek",
  "find",
  "discover",
  "uncover",
  "reveal",
  "expose",
  "disclose",
  "declare",
  "proclaim",
  "announce",
  "state",
  "express",
  "articulate",
  "voice",
  "speak",
  "talk",
  "communicate",
  "share",
  "exchange",
  "interact",
  "engage",
  "participate",
  "involve",
  "include",
  "incorporate",
  "integrate",
  "unify",
  "unite",
  "join",
  "connect",
  "link",
  "bind",
  "tie",
  "fasten",
  "secure",
  "anchor",
  "ground",
  "root",
  "base",
  "foundation",
  "pillar",
  "column",
  "post",
  "beam",
  "support",
  "structure",
  "framework",
  "skeleton",
  "backbone",
  "core",
  "center",
  "middle",
  "heart",
]

const suffixes = [
  "tech",
  "digital",
  "media",
  "news",
  "truth",
  "facts",
  "data",
  "info",
  "network",
  "hub",
  "central",
  "center",
  "hq",
  "base",
  "home",
  "place",
  "space",
  "zone",
  "area",
  "region",
  "nation",
  "country",
  "state",
  "city",
  "town",
  "village",
  "community",
  "society",
  "group",
  "team",
  "crew",
  "squad",
  "force",
  "unit",
  "division",
  "corps",
  "legion",
  "army",
  "navy",
  "air",
  "space",
  "marine",
  "guard",
  "patrol",
  "watch",
  "shield",
  "defense",
  "protect",
  "secure",
  "safe",
  "liberty",
  "freedom",
  "rights",
  "justice",
  "law",
  "order",
  "peace",
  "unity",
  "alliance",
  "coalition",
  "federation",
  "union",
  "league",
  "association",
  "organization",
  "foundation",
  "institute",
  "academy",
  "school",
  "college",
  "university",
  "education",
  "learning",
  "knowledge",
  "wisdom",
  "insight",
  "vision",
  "view",
  "perspective",
  "outlook",
  "approach",
  "method",
  "system",
  "process",
  "procedure",
  "protocol",
  "standard",
  "guide",
  "manual",
  "handbook",
  "reference",
  "resource",
  "tool",
  "utility",
  "service",
  "solution",
  "answer",
  "response",
  "reaction",
  "action",
  "movement",
  "initiative",
  "project",
  "program",
  "plan",
  "strategy",
  "tactic",
  "maneuver",
  "operation",
  "mission",
  "quest",
  "journey",
  "adventure",
  "expedition",
  "exploration",
  "discovery",
  "finding",
  "revelation",
  "disclosure",
  "expose",
  "report",
  "account",
  "story",
  "narrative",
  "chronicle",
  "history",
  "record",
  "document",
  "file",
  "archive",
  "collection",
  "compilation",
  "anthology",
  "series",
  "set",
  "array",
  "assortment",
  "variety",
  "diversity",
  "range",
  "spectrum",
  "scale",
  "measure",
  "metric",
  "standard",
  "benchmark",
  "criterion",
  "principle",
  "value",
  "virtue",
  "quality",
  "attribute",
  "trait",
  "characteristic",
  "feature",
  "aspect",
  "element",
  "component",
  "part",
  "piece",
  "segment",
  "section",
  "division",
  "unit",
  "module",
  "block",
  "node",
  "point",
  "spot",
  "location",
  "position",
  "place",
  "site",
  "venue",
  "arena",
  "field",
  "ground",
  "land",
  "territory",
  "domain",
  "realm",
  "kingdom",
  "empire",
  "dynasty",
  "legacy",
  "heritage",
  "tradition",
  "custom",
  "practice",
  "habit",
  "routine",
  "ritual",
  "ceremony",
  "celebration",
  "commemoration",
  "memorial",
  "monument",
  "landmark",
  "beacon",
  "signal",
  "sign",
  "symbol",
  "emblem",
  "badge",
  "insignia",
  "crest",
  "coat",
  "shield",
  "banner",
  "flag",
  "standard",
  "ensign",
  "colors",
  "mark",
  "brand",
  "label",
  "tag",
  "stamp",
  "seal",
  "imprint",
  "impression",
  "image",
  "picture",
  "portrait",
  "photo",
  "snapshot",
  "shot",
  "frame",
  "scene",
  "view",
  "vista",
  "panorama",
  "landscape",
  "horizon",
  "sky",
  "heaven",
  "paradise",
  "utopia",
  "ideal",
  "dream",
  "vision",
  "aspiration",
  "hope",
  "wish",
  "desire",
  "want",
  "need",
  "requirement",
  "necessity",
  "essential",
  "fundamental",
  "basic",
  "core",
  "central",
  "key",
  "critical",
  "crucial",
  "vital",
  "important",
  "significant",
  "major",
  "main",
  "primary",
  "principal",
  "chief",
  "head",
  "lead",
  "top",
  "premier",
  "prime",
  "first",
  "foremost",
  "supreme",
  "ultimate",
  "absolute",
  "total",
  "complete",
  "whole",
  "entire",
  "full",
  "comprehensive",
  "thorough",
  "extensive",
  "broad",
  "wide",
  "vast",
  "immense",
  "enormous",
  "huge",
  "massive",
  "colossal",
  "gigantic",
  "giant",
  "big",
  "large",
  "great",
  "grand",
  "magnificent",
  "splendid",
  "superb",
  "excellent",
  "outstanding",
  "exceptional",
  "extraordinary",
  "remarkable",
  "notable",
  "noteworthy",
  "significant",
  "important",
  "consequential",
  "momentous",
  "historic",
  "historical",
  "legendary",
  "fabled",
  "storied",
  "famous",
  "renowned",
  "celebrated",
  "acclaimed",
  "distinguished",
  "eminent",
  "prominent",
  "preeminent",
  "leading",
  "foremost",
  "premier",
  "prime",
  "primary",
  "principal",
  "chief",
  "main",
  "major",
  "key",
  "central",
  "core",
  "essential",
  "fundamental",
  "basic",
  "elemental",
  "rudimentary",
  "primitive",
  "primal",
  "original",
  "initial",
  "first",
  "earliest",
  "ancient",
  "old",
  "traditional",
  "conventional",
  "standard",
  "regular",
  "normal",
  "usual",
  "common",
  "ordinary",
  "everyday",
  "routine",
  "familiar",
  "known",
  "recognized",
  "established",
  "settled",
  "fixed",
  "set",
  "determined",
  "decided",
  "resolved",
  "concluded",
  "finished",
  "completed",
  "ended",
  "terminated",
  "ceased",
  "stopped",
  "halted",
  "paused",
  "suspended",
  "interrupted",
  "broken",
  "disrupted",
  "disturbed",
  "troubled",
  "concerned",
  "worried",
  "anxious",
  "nervous",
  "tense",
  "stressed",
  "pressured",
  "burdened",
  "loaded",
  "weighed",
  "heavy",
  "substantial",
  "considerable",
  "significant",
  "appreciable",
  "noticeable",
  "observable",
  "visible",
  "apparent",
  "evident",
  "obvious",
  "clear",
  "plain",
  "distinct",
  "definite",
  "certain",
  "sure",
  "positive",
  "confident",
  "assured",
  "convinced",
  "persuaded",
  "satisfied",
  "content",
  "happy",
  "pleased",
  "glad",
  "delighted",
  "joyful",
  "cheerful",
  "merry",
  "jolly",
  "jovial",
  "genial",
  "cordial",
  "friendly",
  "amiable",
  "affable",
  "pleasant",
  "agreeable",
  "nice",
  "kind",
  "gentle",
  "tender",
  "soft",
  "mild",
  "moderate",
  "temperate",
  "balanced",
  "even",
  "level",
  "steady",
  "stable",
  "secure",
  "safe",
  "protected",
  "sheltered",
  "shielded",
  "guarded",
  "defended",
  "fortified",
  "reinforced",
  "strengthened",
  "bolstered",
  "supported",
  "backed",
  "upheld",
  "maintained",
  "sustained",
  "preserved",
  "conserved",
  "saved",
  "rescued",
  "recovered",
  "retrieved",
  "regained",
  "reclaimed",
  "restored",
  "renewed",
  "revived",
  "revitalized",
  "rejuvenated",
  "refreshed",
  "invigorated",
  "energized",
  "activated",
  "stimulated",
  "aroused",
  "excited",
  "thrilled",
  "enthralled",
  "captivated",
  "fascinated",
  "entranced",
  "spellbound",
  "mesmerized",
  "hypnotized",
  "bewitched",
  "enchanted",
  "charmed",
]

const tlds = ["com", "org", "net", "io", "co", "app", "dev", "tech", "info", "us", "me", "ai", "edu"]
const categories = ["organization", "company", "education", "technology", "network"]

// Initial set of domains for immediate display
const INITIAL_DOMAINS = [
  { name: "freedom.org", category: "organization" },
  { name: "liberty-tech.com", category: "company" },
  { name: "patriot-university.edu", category: "education" },
  { name: "truth-network.org", category: "organization" },
  { name: "sovereign-systems.io", category: "technology" },
  { name: "heritage-alliance.org", category: "organization" },
  { name: "liberty-college.edu", category: "education" },
  { name: "constitutional-rights.org", category: "organization" },
  { name: "digital-sovereignty.com", category: "company" },
  { name: "parallel-economy.net", category: "network" },
  { name: "faith-freedom.org", category: "organization" },
  { name: "american-values.com", category: "company" },
  { name: "truth-archives.org", category: "organization" },
  { name: "decentralized-future.io", category: "technology" },
  { name: "free-speech-platform.com", category: "company" },
  { name: "patriot-media.org", category: "organization" },
  { name: "liberty-foundation.org", category: "organization" },
  { name: "freedom-press.com", category: "company" },
  { name: "sovereign-citizen.net", category: "network" },
  { name: "constitution-first.org", category: "organization" },
  { name: "american-heritage.edu", category: "education" },
  { name: "truth-seekers.net", category: "network" },
  { name: "liberty-news.com", category: "company" },
  { name: "freedom-tech.io", category: "technology" },
  { name: "patriot-network.org", category: "organization" },
  { name: "sovereign-nation.com", category: "company" },
  { name: "freedom-alliance.org", category: "organization" },
  { name: "liberty-institute.edu", category: "education" },
  { name: "american-values.org", category: "organization" },
  { name: "truth-media.com", category: "company" },
  { name: "patriot-forum.net", category: "network" },
  { name: "freedom-university.edu", category: "education" },
  { name: "liberty-press.org", category: "organization" },
  { name: "sovereign-tech.io", category: "technology" },
  { name: "constitution-defenders.com", category: "company" },
  { name: "american-freedom.org", category: "organization" },
  { name: "truth-coalition.net", category: "network" },
  { name: "liberty-digital.com", category: "company" },
  { name: "freedom-network.org", category: "organization" },
  { name: "patriot-tech.io", category: "technology" },
  { name: "sovereign-media.com", category: "company" },
  { name: "freedom-institute.edu", category: "education" },
  { name: "liberty-nation.org", category: "organization" },
  { name: "american-truth.net", category: "network" },
  { name: "truth-university.edu", category: "education" },
  { name: "patriot-press.com", category: "company" },
  { name: "sovereign-alliance.org", category: "organization" },
  { name: "freedom-coalition.net", category: "network" },
  { name: "liberty-media.com", category: "company" },
  { name: "american-patriot.org", category: "organization" },
]

/**
 * Generate a unique domain name
 */
export function generateDomain(): { name: string; category: string } {
  // Get random prefix and suffix
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)]
  const suffix = suffixes[Math.floor(Math.random() * suffixes.length)]
  const tld = tlds[Math.floor(Math.random() * tlds.length)]
  const category = categories[Math.floor(Math.random() * categories.length)]

  // Create domain name with optional hyphen
  const useHyphen = Math.random() > 0.7
  const domainName = useHyphen ? `${prefix}-${suffix}.${tld}` : `${prefix}${suffix}.${tld}`

  return { name: domainName, category }
}

/**
 * Generate a specified number of unique domains
 */
export function generateUniqueDomains(count: number): { name: string; category: string }[] {
  const domains = new Set<string>()
  const result: { name: string; category: string }[] = []

  // Start with initial domains
  for (const domain of INITIAL_DOMAINS) {
    domains.add(domain.name)
    result.push(domain)
  }

  // Generate additional domains until we reach the target count
  let attempts = 0
  const maxAttempts = count * 2 // Prevent infinite loops

  while (result.length < count && attempts < maxAttempts) {
    attempts++
    const domain = generateDomain()
    if (!domains.has(domain.name)) {
      domains.add(domain.name)
      result.push(domain)
    }
  }

  return result
}

/**
 * Generate all domains for the application
 * This is a memoized function that will only generate domains once
 */
let allDomainsCache: { name: string; category: string }[] | null = null

export function generateAllDomains(): { name: string; category: string }[] {
  if (allDomainsCache) {
    return allDomainsCache
  }

  const domains = generateUniqueDomains(670)
  allDomainsCache = domains
  return domains
}

/**
 * Get a batch of domains for virtualized rendering
 */
export function getDomainBatch(
  allDomains: { name: string; category: string }[],
  startIndex: number,
  count: number,
): { name: string; category: string }[] {
  return allDomains.slice(startIndex, startIndex + count)
}
